package geometricas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 ** Programa con Frontend y Backend, que permita calcular el area y perimetro de las siguientes figuras: 
 *  +Rectangulo. 
 *  +Circulo.
 *  +Cuadrado. 
 * Un boton para: 
 *  -Cada figura.
 *  -Limpiar.
 * Un label que muestra el:
 *  -Nombre de la figura.
 *  -Area y perimetro.
 * Eventos:
 *  +Cambiar el color del boton cuando el mouse se superponga.
 *  +Solicitar y leer los datos mediante cuadros de dialogo.
 *  +Imprima el area y perimetro mediante cuadros de dialogo.
 * @author Ricardo Daniel Hernández Sosa (PlansVsAngry999).
 */
public class Geometricas extends javax.swing.JFrame {
    public Geometricas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnCirculo = new javax.swing.JButton();
        btnCuadrado = new javax.swing.JButton();
        lblPerimetro = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnRectangulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(36, 38, 44));

        jPanel1.setBackground(new java.awt.Color(44, 70, 103));

        btnCirculo.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        btnCirculo.setText("Circulo");
        btnCirculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCirculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCirculoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCirculoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCirculoMouseExited(evt);
            }
        });

        btnCuadrado.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        btnCuadrado.setText("Cuadrado");
        btnCuadrado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCuadrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCuadradoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCuadradoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCuadradoMouseExited(evt);
            }
        });

        lblPerimetro.setBackground(new java.awt.Color(36, 38, 44));
        lblPerimetro.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        lblPerimetro.setForeground(new java.awt.Color(255, 255, 255));
        lblPerimetro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPerimetro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPerimetro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lblPerimetro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPerimetro.setOpaque(true);

        lblArea.setBackground(new java.awt.Color(36, 38, 44));
        lblArea.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lblArea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblArea.setOpaque(true);

        lblTitulo2.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(228, 228, 228));
        lblTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo2.setText("¿Con que figura deseas trabajar?");
        lblTitulo2.setToolTipText("");
        lblTitulo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTitulo.setFont(new java.awt.Font("Bauhaus 93", 0, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Figuras Geometricas");
        lblTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitulo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geometricas/icons/equis.png"))); // NOI18N
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });

        btnRectangulo.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        btnRectangulo.setText("Rectangulo");
        btnRectangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRectanguloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRectanguloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRectanguloMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCuadrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCirculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRectangulo)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo2)
                .addGap(18, 18, 18)
                .addComponent(lblPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCuadrado)
                    .addComponent(btnCirculo)
                    .addComponent(btnRectangulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCuadradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuadradoMouseClicked
            //Limpiar label's de resultado.
       lblPerimetro.setText(null);
       lblArea.setText(null);
            //Declarar datos.
       double area, perimetro, lado;
            //Solicitar datos.
       lado = Double.parseDouble(JOptionPane.showInputDialog(null,"Ingresa el valor del lado..."));
             //Area y perimetro del cuadrado.
        area = lado * lado;
        perimetro = 4*lado;
            //Muestra los datos al usuario
        lblPerimetro.setText("Perimetro = " + perimetro + "\n");
        lblArea.setText("Area = " + area + "\n");
        lblTitulo2.setText("RESULTADOS..."); //Toque estético
    }//GEN-LAST:event_btnCuadradoMouseClicked

    private void btnCirculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCirculoMouseClicked
            //Limpiar label's de resultado.
       lblPerimetro.setText(null);
       lblArea.setText(null);
            //Declarar datos.
       double radio, perimetro, area;
       double pi = 3.14159265358979323846;
            // Solicitar datos..
       radio = Double.parseDouble(JOptionPane.showInputDialog(null,"Ingresa el valor del radio..."));
            //Area y perimetro del circulo.
       perimetro = 2 * (pi * radio);
       area = pi * (radio * radio);
            //Muestra los datos al usuario
       lblPerimetro.setText("Perimetro = " + perimetro + "\n");
       lblArea.setText("Area = " + area + "\n");
       lblTitulo2.setText("RESULTADOS..."); //Toque estético
    }//GEN-LAST:event_btnCirculoMouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
            //Limpiar label's de resultado.
       lblPerimetro.setText(null);
       lblArea.setText(null);
       lblTitulo2.setText("¿Con que figura deseas trabajar?");
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnRectanguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRectanguloMouseClicked
             //Limpiar label's de resultado.
       lblPerimetro.setText(null);
       lblArea.setText(null);
             //Declarar datos.
       double area, perimetro, base, altura;
            //Solicitar datos.
       base = Double.parseDouble(JOptionPane.showInputDialog(null,"Ingresa el valor de la base..."));
       altura = Double.parseDouble(JOptionPane.showInputDialog(null,"Ingresa el valor de la altura..."));
            //Area y perimetro del rectángulo.
        area = base * altura;
        perimetro = (2 * base) + (2 * altura);
             //Muestra los datos al usuario
        lblPerimetro.setText("Perimetro = " + perimetro + "\n");
        lblArea.setText("Area = " + area + "\n");
        lblTitulo2.setText("RESULTADOS..."); //Toque estético
    }//GEN-LAST:event_btnRectanguloMouseClicked
    //COLOREO de btnRectangulo.
    private void btnRectanguloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRectanguloMouseEntered
        //Hue = Matiz.
        //Saturation = Saturacion.
        //Brightness (or Value) = Brillo.
        //Se puede colocar con variables o digitar los numeros (mas sintético con variables).
        btnRectangulo.setBackground(Color.getHSBColor(0.7416666f, 0.5f,0.63f));
    }//GEN-LAST:event_btnRectanguloMouseEntered

    private void btnRectanguloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRectanguloMouseExited
        btnRectangulo.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnRectanguloMouseExited
    //Coloreo de btnCirculo.
    private void btnCirculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCirculoMouseEntered
        btnCirculo.setBackground(Color.getHSBColor(0.5916666f, 0.77f,0.76f));
    }//GEN-LAST:event_btnCirculoMouseEntered

    private void btnCirculoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCirculoMouseExited
        btnCirculo.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnCirculoMouseExited
    //Coloreo de btnCuadrado.
    private void btnCuadradoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuadradoMouseEntered
        btnCuadrado.setBackground(Color.getHSBColor(0f, 0.77f,0.76f));
    }//GEN-LAST:event_btnCuadradoMouseEntered

    private void btnCuadradoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuadradoMouseExited
        btnCuadrado.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnCuadradoMouseExited
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Geometricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Geometricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Geometricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Geometricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Geometricas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCirculo;
    private javax.swing.JButton btnCuadrado;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRectangulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblPerimetro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    // End of variables declaration//GEN-END:variables
}
